[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "nicegui[highcharts]>=3.14.0",
    "pandas>=3.0.3",
    "yfinance>=1.5.1",
]

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.3.260530",
    "ruff>=0.15.21",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
